openapi: 3.0.0
info:
  title: vereteno API
  description: vereteno e-commerce API
  version: 1.0-beta
servers:
  - url: 'http://1467739-cx71348.tw1.ru/api/'
paths:
  /product:
    get:
      summary: Returns a list of products.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

